# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Beginning sync from GitHub to DevOps
  displayName: 'Run a one-line script'

- script: |
    $sourceURL = "https://$(GitHubPAT)@$(GitHubRepo)"
    echo $sourceURL
    $destinationURL = "https://$(AzureDevOpsPAT)@$(AzureDevOpsRepo)"
    git clone --mirror $sourceURL
    git remote rm origin
    git remote add --mirror=fetch origin $destinationURL
    git fetch $sourceURL
    git push origin --all -f 
  displayName: 'Run a multi-line script'
