# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Beginning sync from GitHub to DevOps
  displayName: 'Run a one-line script'

- script: |
    git clone --mirror https://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@github.com/deryck1228/DocumentGenerator3.git
    git remote rm origin
    git remote add --mirror=fetch origin https://27det74nzg7dmrmwikyz7utlj7psmceqws5fqvcr5rbtcrjqkqea@dev.azure.com/QuandaryCG/_git/Quandary%20Document%20Generator
    git fetch https://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@github.com/deryck1228/DocumentGenerator3.git
    git push origin --all -f 
  displayName: 'Run a multi-line script'
